---
- hosts: localhost
  vars_prompt:
  - name: filesize
    prompt: "Enter the file size in megabytes"
    private: no
  tasks:
  - name: Check if file size is valid
    assert:
      that:
        - (filesize | int) <= 100 
        - (filesize | int) >= 1 
      fail_msg: "File size must be between 0 and 100"
      success_msg: "File size is valid, lets proceed"
  - name: create a file
    command: dd if=/dev/zero of=/bigfile bs=1 count={{ filesize }}
