---
- name: variables demo
  gather_facts: false
  vars_files:
    - varfile
  hosts: all
  tasks:
    - name: creating user {{ myuser }}
      user:
        name: "{{ myuser }}"
        shell: /bin/bash
